name: Deploy Flask Website

on:
  push:
    branches: [ main ]  # Adjust if your default branch is different
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask markdown
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Create static site
      run: |
        # Create output directory
        mkdir -p _site
        
        # Copy static files
        mkdir -p _site/static
        cp -r static/* _site/static/ || echo "No static directory found"
        
        # Create simple index.html
        cat > _site/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>My Pathfinder World</title>
            <link rel="stylesheet" href="./static/style.css">
            <link href="https://fonts.googleapis.com/css?family=Cinzel:400,700&display=swap" rel="stylesheet">
        </head>
        <body>
            <div class="container">
                <div class="scroll">
                    <!-- Content will be added here -->
                    <h1>My Pathfinder World</h1>
                    <p>This is a placeholder. Replace with your actual content.</p>
                </div>
            </div>
        </body>
        </html>
        EOF
        
        # Add .nojekyll file
        touch _site/.nojekyll
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        force_orphan: true

    - name: Add .nojekyll file
      run: touch _site/.nojekyll